export enum EObservacion {
    DOCUMENTACION_INCORRECTA = "LA DOCUMENTACIÓN AGREGADA NO CUMPLE LOS REQUISITOS SOLICITADOS",
    CANJE_OBSERVADO = "LA DOCUMENTACIÓN AGREGADA NO CUMPLE LOS REQUISITOS SOLICITADOS",
    REEMBOLSO_OBSERVADO = "LA DOCUMENTACIÓN AGREGADA NO CUMPLE LOS REQUISITOS SOLICITADOS"
}